### ISSUE TITLE
[REQUEST] - Allow Server-Based Configuration

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/discord-bot#144]
# Feature Request

## Is your feature request related to a problem? Please describe:

Currently all command-related configuration (prefix, log channels, etc) are hard-coded into the `config.json` file. The bot should be refactored to allow server-specific configurations.

## Describe the solution you'd like

This could be done by leveraging the database.

**Comment by danielsolartech** [comment]
Can you assign me this?

**Comment by nhcarrigan** [comment]
You are assigned 😁
