### ISSUE TITLE
[REQUEST] - Opt Out

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/discord-bot#150]
# Feature Request

## Is your feature request related to a problem? Please describe:

The bot should be configured to allow users to opt out of data collection (through the usage and level listeners).

## Describe the solution you'd like

We can store opt-out IDs in an array in the config file. When a user talks, the bot should confirm the ID is not in the opt-out array prior to firing the usage and levels listeners.

**Comment by LandonLloyd** [comment]
Hmmm... This looks good. Is this like a command for the bot. Does this require typescript. I would like to take a look but might not get anything. 😬

**Comment by nhcarrigan** [comment]
Yeah, I think the best approach here will be using a command and adding the user ID to the database to opt out. 

(Or using a .env variable, and requiring users contact me directly).

**Comment by LandonLloyd** [comment]
Yeah... That seems pretty complicated. Might be better for someone else to do it.

**Comment by adprasad** [comment]
@nhcarrigan I'd like to give this a try, can you assign it to me?

**Comment by nhcarrigan** [comment]
Sure thing!
