### ISSUE TITLE
[BUG] - Adjust `ping` calculation

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/discord-bot#166]
# Bug Report

## Describe the bug

With the addition of the "typing" delay, the `ping` command now results in an additional 3000ms difference.

## Expected behavior

The command will need to be adjusted to account for the delay when calculating response time.

**Comment by LandonLloyd** [comment]
I can take a look at this one!

**Comment by nhcarrigan** [comment]
I will go ahead and assign this to you 🙂

**Comment by nhcarrigan** [comment]
Closed in #185
