### ISSUE TITLE
[REQUEST] - Add invite command

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/discord-bot#167]
# Feature Request

## Is your feature request related to a problem? Please describe:

This request is to add an invite command to the bot. The bot should respond with an invite link to allows users to bring the bot into their server.

## Describe the solution you'd like

The link can be sent directly as Discord should auto-embed it. Use this link for the feature: https://discord.com/api/oauth2/authorize?client_id=716707753090875473&permissions=268511254&scope=bot

**Comment by danielsolartech** [comment]
I wish make it, please can you assign me this?

**Comment by nhcarrigan** [comment]
You are now assigned 😁
