### ISSUE TITLE
[BUG] - Fix Welcome Command

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/discord-bot#176]
# Bug Report

## Describe the bug

Due to the way Discord handles caching, if a user has left the server the welcome message will no longer display their username.

## Expected behavior

The welcome message needs to be refactored to match the goodbye message, so that it displays the user's username in `string` format instead of a mention.

## Screenshots

![image](https://user-images.githubusercontent.com/63889819/94480392-1b989b00-018b-11eb-8545-ec47c41946a5.png)

**Comment by shadowtime2000** [comment]
I can take a go at this. Should it surround the user's name with code blocks instead? I think it might look a little neater.

**Comment by nhcarrigan** [comment]
Sure that's a good idea! I'll go ahead and assign you. 😁
