### ISSUE TITLE
[Request] Automatic Command Import

### ISSUE THREAD

**Issue by danielsolartech** [nhcarrigan/discord-bot#178]
# Function request

## Is your feature request related to a problem?  Please describe:

Looking at the code I can suggest to do an automatic command import.

## Describe the solution you would like

In `/src/COMMANDS.ts` there are command imports with the same interface (CommandInt).  They can be replaced by an automatic import from the `./src/commands/ `and add them to an array.

This reduces file modifications and is faster for beginners (it only does a single file).

> I can do this for the Hacktoberfest if you wish.

**Comment by nhcarrigan** [comment]
Sure! Sounds good!

**Comment by danielsolartech** [comment]
So, can you assign me this as well?
