### ISSUE TITLE
[REQUEST] - Remove Welcome DM

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/discord-bot#183]
# Feature Request

## Is your feature request related to a problem? Please describe:

Welcome DMs are somewhat of a grey area for the Discord ToS (and general good practise). The bot is currently configured to send a DM embed to a user when they join a server the bot is in, and send a welcome embed inside the server.

## Describe the solution you'd like

The server based welcome embed *should remain*, but the DM embed *should be removed*.

**Comment by zephy20** [comment]
May I take this? :D

**Comment by nhcarrigan** [comment]
All yours!

**Comment by nhcarrigan** [comment]
Closed via #184
