### ISSUE TITLE
[REQUEST] - Among Us command

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/discord-bot#189]
# Feature Request

## Describe the solution you'd like

Add an Among Us related command (maybe `|sus`?). The command should return a message such as "Purple is sus". The colours could be chosen at random from an array (either stored within the command or in a separate file).

## Additional context

nhcarrigan seems sus 👀

**Comment by zgunz42** [comment]
I like work with this issue

**Comment by nhcarrigan** [comment]
Sure! 🙂

**Comment by LandonLloyd** [comment]
Is someone still working on this?

**Comment by nhcarrigan** [comment]
@zgunz42 are you working on this feature?

**Comment by LandonLloyd** [comment]
I can do it... At least I can try.

**Comment by nhcarrigan** [comment]
Closed via #221
