### ISSUE TITLE
[BUG] - Riddle and Challenge command improperly handle bad responses

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/discord-bot#194]
# Bug Report

## Describe the bug

The APIs for these commands are designed to return a JSON object with an `error` property when a user provides the wrong answer. The `challenge` command handles this in a `catch` statement while the `riddle` command crashes. Neither of these commands are properly displaying the response to the user.

## Expected behavior

Both commands need to be adjusted to provide the feedback to the user regarding their command. Additionally, the `riddle` command needs to take the full answer (instead of using `.shift()`).

**Comment by Andreybest** [comment]
Hello! I'd like to work to fix this issue! Can you assign this task to me?

**Comment by nhcarrigan** [comment]
Sure!
