### ISSUE TITLE
[BUG] usage command/listener

### ISSUE THREAD

**Issue by danielsolartech** [nhcarrigan/discord-bot#204]
# Bug Report

## Describe the bug

The usage listener does not register the command usage.

(At the moment i cannot find what produces this error)

## Screenshots

![Image](https://i.imgur.com/gR8rrJD.png)

**Comment by nhcarrigan** [comment]
While this is being poked at, let's ensure that these values are *not* server specific. 

The idea here is to track command usage globally to determine which features are most popular, and use that data to help determine the future development roadmap.

**Comment by adprasad** [comment]
I think this is a data issue. The server_id fields is required now in the Mongoose schema where previously it was not. So existing records/entries which do not have the server id won't be returned.

**Comment by adprasad** [comment]
looking again at the code and how the listeners are grabbed the issues is the name of the intercepted listener should match the name of the file (both level and usage) rather than the original function/const name
