### ISSUE TITLE
I see that there is a bug in the command |trivia

### ISSUE THREAD

**Issue by ved08** [nhcarrigan/discord-bot#97]
## Describe the bug
When I start the quiz using |trivia, I get a question (no problem there). But when I message all the 4 options, then it says that I am the winner.

## Expected behavior
I expect that a user can only enter their option once.

## Screenshots
![Screenshot_20200820-134943](https://user-images.githubusercontent.com/37742218/90739228-381ff880-e2ec-11ea-8307-f0ad9178436a.png)

**Comment by nhcarrigan** [comment]
This should be fixed now! 😀

**Comment by ved08** [comment]
👍
